### PR TITLE
Added Space between the words in Heading

### PR DESCRIPTION
**Pull request by rsrinath14**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
This looks better 👍 , any reason why it was closed?

**Comment by srinath1412001** [comment]
I felt it didn't add that much value. I had made this PR to complete a daily challenge in MLH Local Day Hack.
I'll open it again.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
> I felt it didn't add that much value

It looks more readable now after your change, so I think it adds value 👍

**Pull request merged**
