### PR TITLE
Spelling Errors

### PR DESCRIPTION
**Pull request by galahad42**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
This looks good 👍 - did you mean to close it?

**Comment by galahad42** [comment]
I wanted to merge it to the master branch

**Comment by eddiejaoude** [comment]
Only the project maintainer(s) can accept & merge PRs.

Now you have reopened it, I can merge it 🤓

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
